name: "Release Binary"

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: "ubuntu-latest"
    name: "Create Release"
    steps:
      - uses: actions/checkout@v4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  build-tar-ball:
    needs: "create-release"
    name: "Build and Tar Ball"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: "openbmclapi-linux.tar.xz"
          - os: windows-latest
            artifact_name: "openbmclapi-windows.tar.xz"
          - os: macos-latest
            artifact_name: "openbmclapi-macos.tar.xz"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: tar -cJf ${{ matrix.artifact_name }} dist nginx package.json node_modules
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}



