name: "Release Binary"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: tar -czvf openbmclapi-${{ matrix.os }}.tar.gz dist nginx package.json node_modules
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: openbmclapi-${{ matrix.os }}.tar.gz



